### ISSUE TITLE
README's

### ISSUE THREAD

**Issue by Nic-Nic** [saezlab/PHONEMeS-ILP#1]
PHONEMeS installation instructions in the main [`README.md`](https://github.com/saezlab/PHONEMeS-ILP/blob/master/README.md) file should be version-independent so users can easily choose/find the stable/other release.

The "documentation" ([`Examples/README.md`](https://github.com/saezlab/PHONEMeS-ILP/blob/master/Examples/README.md)) doesn't explain much about the ACTUAL data input (e.g. only says download the example data, but what about if user wants to use its own data?) like which formats are supported (`.csv`, `.txt`...)? what kind of data (intensities, logFC, ...)? and in which disposition (samples/readouts in columns/rows)? Similar description for the kinase-substrate network file also would be nice.
Also, is there any other mandatory/optional user input (e.g. p-value threshold, etc)?
Would also help if the whole pipeline is described for any given (generic) dataset in a step-wise fashion like a numbered list.
You also mention a folder named "Codes" containing the scripts `buildDataMatrix.R` and `executionScript.R` but no such folder exists.

**Comment by NotValdemaras** [comment]
I would like to second this issue. Making a step-wise tutorial on how to set up your own data for the analysis would be greatly appreciated.
